In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("/content/titanic uncleaned (1).csv")

In [ ]:
df

,Store,Country,State,City,Category,Clothing Type,Store Number,Postal Code,Store Type,Store Open Date,...,Security Features,Order ID,Order Date,Month,Customer ID,Customer Name,Product ID,Price,Quantity,Sales Profit
0,Zudio,India,Karnataka,Jalna,Women,Dresses,30,411084,Owned,2022-06-04,...,Alarm,88240.0,2024-11-06,November,233084.0,Michele Ochoa,354.0,1958.0,5.0,3916.0
1,Zudio,India,Gujarat,Patna,Kids,Skirts,48,404562,Owned,2020-12-19,...,Alarm,78145.0,2024-06-17,June,926472.0,Daniel Jimenez,741.0,2078.0,1.0,831.2
2,Zudio,India,Uttar Pradesh,Kolkata,Men,Hoodies,97,437773,Rented,2023-09-04,...,CCTV,33363.0,2024-08-17,August,853255.0,Steven Davis,607.0,1445.0,2.0,1156.0
3,Zudio,India,West Bengal,Kolkata,Women,Dresses,93,431725,Owned,2024-04-11,...,CCTV,46682.0,2024-03-27,March,106146.0,Derek Orozco,991.0,2469.0,6.0,5925.6
4,Zudio,India,West Bengal,Guwahati,Men,Dresses,51,415370,Owned,2022-05-29,...,"CCTV, Alarm",58242.0,2024-04-08,April,264070.0,Victor Arnold,479.0,1105.0,6.0,2652.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4043,Zudio,India,Delhi,Mumbai,Men,Shoes,22,431683,Rented,2020-03-27,...,NaN,96439.0,2024-01-03,January,869305.0,Derrick Sims,513.0,821.0,1.0,328.4
4044,Zudio,India,Rajasthan,Agra,Kids,Tops,92,425037,Owned,2022-02-01,...,Alarm,56333.0,2024-03-01,March,499296.0,Amy Oconnell,936.0,1599.0,6.0,3837.6
4045,Zudio,India,Delhi,Kanpur,Men,T-shirts,75,426200,Owned,2021-08-01,...,CCTV,28714.0,2024-04-12,April,188191.0,Christopher Russo,874.0,2985.0,2.0,2388.0
4046,Zudio,India,Uttar Pradesh,Chhattisgarh,Kids,Pants,75,426806,Owned,2023-08-14,...,"CCTV, Alarm",59230.0,2024-10-24,October,270529.0,Jeffrey Daugherty,648.0,2182.0,2.0,1745.6
4047,Zudio,India,Delhi,Coimbatore,Women,Skirts,60,403285,Rented,2020-07-19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.head(10)

,Store,Country,State,City,Category,Clothing Type,Store Number,Postal Code,Store Type,Store Open Date,...,Security Features,Order ID,Order Date,Month,Customer ID,Customer Name,Product ID,Price,Quantity,Sales Profit
0,Zudio,India,Karnataka,Jalna,Women,Dresses,30,411084,Owned,2022-06-04,...,Alarm,88240.0,2024-11-06,November,233084.0,Michele Ochoa,354.0,1958.0,5.0,3916.0
1,Zudio,India,Gujarat,Patna,Kids,Skirts,48,404562,Owned,2020-12-19,...,Alarm,78145.0,2024-06-17,June,926472.0,Daniel Jimenez,741.0,2078.0,1.0,831.2
2,Zudio,India,Uttar Pradesh,Kolkata,Men,Hoodies,97,437773,Rented,2023-09-04,...,CCTV,33363.0,2024-08-17,August,853255.0,Steven Davis,607.0,1445.0,2.0,1156.0
3,Zudio,India,West Bengal,Kolkata,Women,Dresses,93,431725,Owned,2024-04-11,...,CCTV,46682.0,2024-03-27,March,106146.0,Derek Orozco,991.0,2469.0,6.0,5925.6
4,Zudio,India,West Bengal,Guwahati,Men,Dresses,51,415370,Owned,2022-05-29,...,"CCTV, Alarm",58242.0,2024-04-08,April,264070.0,Victor Arnold,479.0,1105.0,6.0,2652.0
5,Zudio,India,West Bengal,Nashik,Kids,Jackets,71,417269,Owned,2021-06-17,...,CCTV,78800.0,2024-04-25,April,326466.0,James Bennett,295.0,2206.0,4.0,3529.6
6,Zudio,India,Maharashtra,Lucknow,Kids,Jackets,44,439184,Rented,2021-04-29,...,CCTV,43329.0,2024-06-19,June,724817.0,Benjamin Barrett,222.0,2848.0,4.0,4556.8
7,Zudio,India,West Bengal,Hyderabad,Women,Tops,74,417964,Owned,2021-11-16,...,CCTV,23062.0,2024-06-11,June,870587.0,Matthew Cervantes,595.0,1694.0,8.0,5420.8
8,Zudio,India,Karnataka,Ahmedabad,Men,Shoes,71,414510,Rented,2023-11-23,...,"CCTV, Alarm",72223.0,2024-01-24,January,790306.0,Shelley Lopez,243.0,2024.0,1.0,809.6
9,Zudio,India,Karnataka,Hyderabad,Kids,Jeans,26,411577,Rented,2021-09-02,...,NaN,35882.0,2024-02-02,February,943541.0,Brandon Sampson,910.0,2581.0,6.0,6194.4

In [ ]:
df.tail(10)

,Store,Country,State,City,Category,Clothing Type,Store Number,Postal Code,Store Type,Store Open Date,...,Security Features,Order ID,Order Date,Month,Customer ID,Customer Name,Product ID,Price,Quantity,Sales Profit
4038,Zudio,India,Uttar Pradesh,Solapur,Women,Hoodies,56,414639,Rented,2024-11-07,...,"CCTV, Alarm",76509.0,2024-03-19,March,182522.0,Krista Smith,280.0,1847.0,3.0,2216.4
4039,Zudio,India,Karnataka,Vadodara,Women,Shirts,45,403634,Rented,2021-11-14,...,"CCTV, Alarm",86335.0,2024-11-01,November,537734.0,Timothy Dixon,562.0,1257.0,7.0,3519.6
4040,Zudio,India,West Bengal,Visakhapatnam,Women,Pants,49,432890,Owned,2020-06-24,...,NaN,39090.0,2024-03-05,March,654886.0,Rebekah Lee,362.0,2311.0,7.0,6470.8
4041,Zudio,India,Maharashtra,Bengaluru,Men,Dresses,55,417045,Rented,2022-09-27,...,Alarm,36744.0,2024-02-07,February,751359.0,Kristine Blevins,810.0,2618.0,1.0,1047.2
4042,Zudio,India,West Bengal,Chennai,Kids,Pants,9,423921,Rented,2023-07-02,...,"CCTV, Alarm",54996.0,2024-09-11,September,999858.0,Diane Munoz,719.0,703.0,5.0,1406.0
4043,Zudio,India,Delhi,Mumbai,Men,Shoes,22,431683,Rented,2020-03-27,...,NaN,96439.0,2024-01-03,January,869305.0,Derrick Sims,513.0,821.0,1.0,328.4
4044,Zudio,India,Rajasthan,Agra,Kids,Tops,92,425037,Owned,2022-02-01,...,Alarm,56333.0,2024-03-01,March,499296.0,Amy Oconnell,936.0,1599.0,6.0,3837.6
4045,Zudio,India,Delhi,Kanpur,Men,T-shirts,75,426200,Owned,2021-08-01,...,CCTV,28714.0,2024-04-12,April,188191.0,Christopher Russo,874.0,2985.0,2.0,2388.0
4046,Zudio,India,Uttar Pradesh,Chhattisgarh,Kids,Pants,75,426806,Owned,2023-08-14,...,"CCTV, Alarm",59230.0,2024-10-24,October,270529.0,Jeffrey Daugherty,648.0,2182.0,2.0,1745.6
4047,Zudio,India,Delhi,Coimbatore,Women,Skirts,60,403285,Rented,2020-07-19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4048 entries, 0 to 4047
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Store                      4048 non-null   object
 1   Country                    4048 non-null   object
 2   State                      4048 non-null   object
 3   City                       4048 non-null   object
 4   Category                   4048 non-null   object
 5   Clothing Type              4048 non-null   object
 6   Store Number               4048 non-null   int64
 7   Postal Code                4048 non-null   int64
 8   Store Type                 4048 non-null   object
 9   Store Open Date            4048 non-null   object
 10  Selling Area Size (sq ft)  4048 non-null   int64
 11  Store Manager              4048 non-null   object
 12  Manager ID                 4048 non-null   object
 13  Store Address              4048 non-null   object
 14  Contact Information        4048 non-null   object
 15  Operating Hours            4048 non-null   object
 16  Staff Count                4048 non-null   int64
 17  Parking Availability       4047 non-null   object
 18  Security Features          2999 non-null   object
 19  Order ID                   4047 non-null   float64
 20  Order Date                 4047 non-null   object
 21  Month                      4047 non-null   object
 22  Customer ID                4047 non-null   float64
 23  Customer Name              4047 non-null   object
 24  Product ID                 4047 non-null   float64
 25  Price                      4047 non-null   float64
 26  Quantity                   4047 non-null   float64
 27  Sales Profit               4047 non-null   float64
dtypes: float64(6), int64(4), object(18)
memory usage: 885.6+ KB

In [ ]:
df.shape

(4048, 28)

In [ ]:
df.dtypes

Store                         object
Country                       object
State                         object
City                          object
Category                      object
Clothing Type                 object
Store Number                   int64
Postal Code                    int64
Store Type                    object
Store Open Date               object
Selling Area Size (sq ft)      int64
Store Manager                 object
Manager ID                    object
Store Address                 object
Contact Information           object
Operating Hours               object
Staff Count                    int64
Parking Availability          object
Security Features             object
Order ID                     float64
Order Date                    object
Month                         object
Customer ID                  float64
Customer Name                 object
Product ID                   float64
Price                        float64
Quantity                     float64
Sales Profit                 float64
dtype: object

In [ ]:
df.describe()

,Store Number,Postal Code,Selling Area Size (sq ft),Staff Count,Order ID,Customer ID,Product ID,Price,Quantity,Sales Profit
count,4048.000000,4048.000000,4048.000000,4048.000000,4047.000000,4047.000000,4047.000000,4047.000000,4047.000000,4047.000000
mean,50.809289,419792.591403,1110.461957,11.404644,55050.624907,549387.995552,599.415122,1752.723499,4.497653,3134.093897
std,29.056427,11704.231124,192.873679,5.176194,26007.573717,263263.866592,233.912268,709.169354,2.279946,2109.461393
min,1.000000,400006.000000,800.000000,3.000000,10008.000000,100271.000000,204.000000,500.000000,1.000000,201.200000
25%,26.000000,409616.500000,950.000000,7.000000,33118.000000,318309.500000,391.000000,1144.000000,3.000000,1431.600000
50%,51.000000,419675.000000,1100.000000,11.000000,54811.000000,546524.000000,601.000000,1765.000000,4.000000,2648.000000
75%,76.000000,430042.250000,1300.000000,16.000000,77675.000000,778313.500000,802.000000,2351.000000,6.000000,4481.600000
max,100.000000,439985.000000,1400.000000,20.000000,99999.000000,999858.000000,999.000000,2999.000000,8.000000,9596.800000

In [ ]:
df['Country']

0       India
1       India
2       India
3       India
4       India
        ...
4043    India
4044    India
4045    India
4046    India
4047    India
Name: Country, Length: 4048, dtype: object

In [ ]:
df[['Country','Month']]

     Country     Month
0      India  November
1      India      June
2      India    August
3      India     March
4      India     April
...      ...       ...
4043   India   January
4044   India     March
4045   India     April
4046   India   October
4047   India       NaN

[4048 rows x 2 columns]